name             'elasticsearch-ng'
maintainer       'Nathan Williams'
maintainer_email 'nath.e.wilL@gmail.com'
license          'apache2'
description      'Installs/Configures elasticsearch-ng'
long_description 'Installs/Configures elasticsearch-ng'
version          '0.1.1'

depends 'apt'
depends 'yum'
depends 'java'
